spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

google:
  maps:
    api-key: dummy-key-not-used-in-tests
    connect-timeout: 3s
    read-timeout: 5s

# Par RSA gerado apenas para testes (openssl), nunca usado fora do profile test.
security:
  jwt:
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCR/UbNZshcYuH2XsWlVp9gr3s/XAoE8fyAfhm1O0sXR3F/VEilwTdYmcyyRxAKeC529UG7slKMaBK381QJpA4rtl6ouBtDABkBeYi9Wb5G0kzFHrXdxhsJKynz2OU/F6VGQDy8Jck/Qu797Awto2cZ629gLKLmpCx1gLbtnbcuN5QiAgZjXqc/yTHRiyVTBfPoP0tGaj1/6QqMTAykAIL/d8PmKUXe2ZmjPJDGUcSe9HNao+pnAHhBQpEIzuoYyUy//HuBqAtsiBNv6ml+QyLmwmxE7DK8KdlRmQXGQlZDhjEIp3V5GqtNbeqHVBV7MeFCIRlMXvBiejkoEiMXJMVlAgMBAAECggEAG5mMlyyFWKIBIjjMmPOFchv66wGVi1XMbOZqKc8p5R7GoFHo4h1jP0bkYhf5OmF6N1cqtDeET7MlRs2j56ayXyU9RBx6WvJbx+GYLmQXCwCbLvEdZO4dEmCsr8MjpAfuYRen49Io9+LJmAvWSZKI3WebSM1nhr8nAJfy/X1BsmTaZcapvu2WsY7aVRJdN9Rwu2AE9Hi1VVSqWiCbDdhWokfn6Cq0mqC+7XYYugm4mirvW3fuowbPm1/6TGL+wPjNzktsdm1w7hmMdagZE+Lsc/FJIVhb97YcNYXBgc7uwqNnUw98P9Uy+USpEX4aCgh0xgKxP/QbrGbUf+NYpHqLAQKBgQDG/zTgsN9RNQ4TX9MyvgUcsSgZ1QsjE8Tn4ICw5d+nTQhDL4zWlPOQukBSccaSZfMK7FyxBF8hFy5mqJYqv5Va5SkbEbEeoC38XphBXLcFecVuaqmopfsMS3cjSowYYLbdrWro+u2tbc3Q0eh8Oswzh84iBQtUjGfBr0jCR/G1xQKBgQC7zu8K4vvaIUL+S8TgOvdTG3iLehkFt+3Ck8P6dR88lpKAAmLQSf6hremk2ffyYUOo2JPLcc6zZRj3QEBzj8JfDO0F5nuWUT0m6Tm4JO+S7qrRaqfBVbyqpngF8qxvsJkmrQplai++ZAivAgKa3EJ+2290BXhP1N0EPySxRSdrIQKBgQCNNs+kX3+qFhdOAmNSj+v6x3Dom/mSQ9YoonVQk2AaThz96IFuSTdqzfEVUG4Ut8o4RzEj4TFMvzGLYjlmTpxDa3m3Ht/tFshrXgl34L50YUyMpZ6N8nNr7yW1YpJ2PjOmrgi/GkqOFuzGMh9kASmlq8rI84Ft11FN7gCY9gr97QKBgCSEdRhx0DS2uPcHNo2/CW4gbkz4fbsN624lGzss4NkAEhZP4HTNnnRDg6WpODvpy6UeD4bEZ0OcicExvhZ6QnoG4mN+UFOHElPpj26NyAOS4qX7jgjaqeeonLfTWtIQzYamqNnVTtk/TCzzQBxqbYeLFV3C3oTvR9ZWjMTnRGXhAoGAGOBc6pRPT1pfWkmjK6BU56EJMvFrcixtiM9FBoKTpknmOrSsu2EqkcjuMH9iqwJ8c1QQ/TCioGJvNU5a6tO67gFSWQ3PkTYAy89cdqYdk3Q150bC/jc3MZPUs9y4zyUkgpNjYSIG3x/q6YdDdHw90tGg69cwgEI7ySsK9cJSxiw=
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkf1GzWbIXGLh9l7FpVafYK97P1wKBPH8gH4ZtTtLF0dxf1RIpcE3WJnMskcQCngudvVBu7JSjGgSt/NUCaQOK7ZeqLgbQwAZAXmIvVm+RtJMxR613cYbCSsp89jlPxelRkA8vCXJP0Lu/ewMLaNnGetvYCyi5qQsdYC27Z23LjeUIgIGY16nP8kx0YslUwXz6D9LRmo9f+kKjEwMpACC/3fD5ilF3tmZozyQxlHEnvRzWqPqZwB4QUKRCM7qGMlMv/x7gagLbIgTb+ppfkMi5sJsROwyvCnZUZkFxkJWQ4YxCKd1eRqrTW3qh1QVezHhQiEZTF7wYno5KBIjFyTFZQIDAQAB
    expiration: 8h

# Chave AES gerada apenas para testes (RNF06), nunca usada fora do profile test.
app:
  security:
    data-encryption-key: DSD19ZTZPPwiQoz43GFQH74U1tq5wSxiMEn22/MH31A=
  storage:
    local-dir: target/test-uploads
