spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

google:
  maps:
    api-key: dummy-key-not-used-in-tests
    connect-timeout: 3s
    read-timeout: 5s

# Par RSA gerado apenas para testes (openssl), nunca usado fora do profile test.
security:
  jwt:
    private-key: MIIEowIBAAKCAQEAso6ZB1dsmgWYveUOyOUuZKc3BLbO3OzjOJ4F3yJJuR5etaXGR5f+bO5ta9+cciXMS5i5WiBH0AnHGxY//pdbTn4aCKa8yUZp8fEP9P3tdLuTa1Ne4aFMRMHFUluMIf+rQhBu5lPEP9/F7EsihxY0nojPHH1fM8Vu9fnCD601Yim+B4o6l9QEClbUbg7mM5zW/xsIU+dfcXApyLgjqgQB8vSzC/2XgYRE+NRH9kKhmh3CgDSIwWjiS1ZCcGYd+AYygmBGvZKdI9Van2YBi1farmBq9jZZiWVEIwPX5WOTXUEK4c6EMoSak2by/HpwfOfF/z6BveL9yEvBCkeWcM+KUwIDAQABAoIBAAZGwZWi0BF17ZGMkgF5H4awOLHfZH7Fi5MmPYSYuvNZNZu4UQjxNyNIb5Y2zP6s2h/fescdPV5QXwGnvZDLFzg3cd4opkLY88kVCn+NHCIEpJZFiZ9Fa93lhcnIUrEF61TY07J1nVS1c/VDYC+payjAxwRJr+VXpPfb004jw4Lzb6TUof4YK2UG0r9PSm3VX0jrp6Db1ljStOnRXTiqpUK22XyU9UYXRQtbsz6yA6b6qPiV2L1JNr8qAWnw5s1sQtNHEK3/gDE7G3Dd3k2/aP2eRwCe2bCV5IkKK5nugEP22Xvm8J4rF5PXZVq0Ks+YtnIqY6lpJ9x0rXaq3OUK9eECgYEA2CxfVA2Eb/9sZB3cWebm14C+MUEC3KmqZv1MjsaeSsbuu2n8/BmoYoKHqctCLyKsKL/3RqybF70msH1WdPW9xSkmbtRvovKLCEeXikeaBZJXklFGxfeun8RCiwuA0UC+GakZyaA0rTQbJMi3smKAlZuJ33o35x6m2nfncSTH3TECgYEA03QVu2EQjUd0tMC6X988Vm/GUBu7JhBeoIvTHFlRbKPE5gbbP1AXZY84XNr2HFf/QZmM3PpS4YRJNpvdiIYSnS87Z2fpps2J9b1qniCxti0LVU2kreUa8H/w1BTiCFQ/XTpJ6jIusQAjHHYxoJtKGyQCz/8yfD0yvrZ+H+Y3bsMCgYEAl89Rgu2bPCvcKtLtlBUbt+uppV1KbTyZdoob4YiKUWky7lqYV1KNdeDE9PDRIdjvng5x0SgWIq2rJfZfaPPKuVMUsnBtlblO+hmMyodOGuuSpCZ/1TcDYx+ou4zwggM9fTfL7FSdqaUWCtcKajPSqT35rP9fkudrtbDO0B5MXYECgYB3gI2fnlWqYo3UcW9jK1iASR88us9jzbCM7zjaNqhLy6pFje5us6blYLGr2JtqnVjHDC6N3HLmvMpbsG7c71ipuL3LzPBBsrubQ/dzcmq82GwlQ4IkPOyiqsvCMCMmLea5m22Wi9HTeo5dUXbum5SgDhQA1OsFR9jb62sQQB1n3QKBgGuU4Kp6KQleWFCOPt+pxFVnb/Sc6Xhzn2jMz6Zk4hdZpQqYi/giFgGewbmHQmB7uG3zaRZb8+A2ky5532nj6QjWVdQGh9X8C127mA+GknzeQq52qjriUh2wE1NvprcttRMdCyKA14iaaWm0tEbNuWCNrU/8RE+ocUFEZ2M6ggVL
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAso6ZB1dsmgWYveUOyOUuZKc3BLbO3OzjOJ4F3yJJuR5etaXGR5f+bO5ta9+cciXMS5i5WiBH0AnHGxY//pdbTn4aCKa8yUZp8fEP9P3tdLuTa1Ne4aFMRMHFUluMIf+rQhBu5lPEP9/F7EsihxY0nojPHH1fM8Vu9fnCD601Yim+B4o6l9QEClbUbg7mM5zW/xsIU+dfcXApyLgjqgQB8vSzC/2XgYRE+NRH9kKhmh3CgDSIwWjiS1ZCcGYd+AYygmBGvZKdI9Van2YBi1farmBq9jZZiWVEIwPX5WOTXUEK4c6EMoSak2by/HpwfOfF/z6BveL9yEvBCkeWcM+KUwIDAQAB
    expiration: 8h
